### ISSUE TITLE
SDK compile error:/usr/bin/ld:../lib/Linux/cpp/x86_64/libxCoreSDK.a: file format not recognized; treating as linker script

### ISSUE THREAD

**Issue by renyu2016** [RokaeRobot/xCoreSDK-CPP#1]
When compile the sdk package using cmake counter following error:
root@rokearobot1:~/catkin_ws/src/rokae_ros/xCoreSDK-CPP# make
[  4%] Linking CXX executable ../bin/sdk_example
/usr/bin/ld:../lib/Linux/cpp/x86_64/libxCoreSDK.a: file format not recognized; treating as linker script
/usr/bin/ld:../lib/Linux/cpp/x86_64/libxCoreSDK.a:1: syntax error
collect2: error: ld returned 1 exit status
make[2]: *** [example/CMakeFiles/sdk_example.dir/build.make:99: bin/sdk_example] Error 1
make[1]: *** [CMakeFiles/Makefile2:207: example/CMakeFiles/sdk_example.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by renyu2016** [comment]
It seems that the repo should be obtained using git clone command instead of downloading zip directly. The problem is solved.

**Comment by 4ku** [comment]
Use git lfs also!
